export const locations = [
  "Entire Delhi/NCR",
  "Entire Delhi",
  "North Delhi",
  "South Delhi",
  "East Delhi",
  "West Delhi",
  "North East Delhi",
  "South East Delhi",
  "North West Delhi",
  "South West Delhi",
  "New Delhi",
  "Central Delhi",
  "Shahdra",
  "Dwarka",
  "Gurgaon",
  "Noida/Greater Noida",
  "Ghaziabad",
  "Faridabad",
];
